baseURL = "https://agathe.cool"
languageCode = "fr-fr"
title = "Agathe Vuachet - DA"
theme = "hallo-cool"
defaultContentLanguage = "fr"

[Author]
name = "Agathe"





[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:salut@agathe.cool"



    [[params.links]]
        icon = "linkedin"
        title = "Linkedin"
        url = "https://www.linkedin.com/in/agatheplus/"
      