baseURL = "https://www.agathe.cool"
languageCode = "fr-fr"
title = "Agathe Vuachet - Ui Designer"
theme = "hallo"
defaultContentLanguage = "fr"

[Author]
name = "Agathe"





[params]
  greeting = "Greetings!"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:salut@agathe.cool"



    [[params.links]]
        icon = "linkedin"
        title = "Linkedin"
        url = "https://www.linkedin.com/in/agatheplus/"
      
      [params.colors]
      background = "#81c6ff"
      foreground = "#edf7ff"
      hover = "#ffba82"
 